# Generated by Django 2.0.5 on 2018-05-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=50, verbose_name='Название комнаты')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_name', models.CharField(max_length=50, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Текст Заявки')),
                ('date_start', models.DateTimeField(verbose_name='Дата создания')),
                ('date_end', models.DateTimeField(verbose_name='Дата закрытия')),
                ('assigned', models.CharField(default='---', max_length=50, verbose_name='Исполнитель')),
                ('created', models.CharField(default='---', max_length=50, verbose_name='Создатель заявки')),
                ('location', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='issues.Place', verbose_name='Местонахождение')),
                ('priority', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='issues.Priority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='issues.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
