# Generated by Django 2.0.5 on 2018-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='Дата закрытия'),
        ),
    ]
