# Generated by Django 2.0.5 on 2018-05-09 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20180509_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['id'], 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
    ]
