# Generated by Django 2.0.5 on 2018-05-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Колличество'),
        ),
    ]
