# Generated by Django 2.0.5 on 2018-05-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180507_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.Item'),
        ),
    ]
