# Generated by Django 2.0.5 on 2018-05-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20180508_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='items',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='task.Item'),
        ),
    ]
