# Generated by Django 2.0.5 on 2018-05-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20180508_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='items',
            field=models.ForeignKey(default='---', on_delete=django.db.models.deletion.CASCADE, to='task.Item', verbose_name='Оборудование'),
        ),
    ]
